services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: computer_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: computer_store
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  pgdata:
